services:
  mysql:
    image: mysql:8.0
    container_name: clap_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  consul:
    image: hashicorp/consul
    container_name: clap-consul
    restart: unless-stopped
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: