server:
  port: 9010

spring:
  application:
    name: social-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.cloud.consul:
  host: consul
  port: 8500
  discovery:
    service-name: social-service
    health-check-path: /actuator/health
    health-check-interval: 10s

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
