spring:
  application:
    name: auth
  datasource:
    url: "jdbc:mysql://mysql:3306/auth_db"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  cloud:
    consul:
      host: consul
      port: 8500

server:
  port: 8090

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
